name: WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    permissions: 
      contents: write  # <--- MUST HAVE THIS to allow saving changes
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # <--- MUST HAVE THIS
          SHOW_LOC_CHART: "False" # Optional: Customize as needed